
services:
  # The main microservice, serving the OpenAI summarizer
  #
  openai-summarizer:
    image: openai-summarizer:${VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=${VERSION}
    environment:
      PYTHON_PATH: /app
    env_file: .env
    ports:
      - "9998:9998"
    dns: 8.8.8.8
    # network_mode: host
    volumes:
      - ./app:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openai-summarizer.rule=Host(`munch-cti.lo-res.org`)"
      - "traefik.http.routers.openai-summarizer.entrypoints=websecure"
      - "traefik.http.routers.openai-summarizer.tls.certresolver=myresolver"
      - "traefik.http.services.openai-summarizer.loadbalancer.server.port=9998"
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
