version: "3"
services:
  # The main microservice, serving the OpenAI summarizer
  #
  openai-summarizer:
    image: openai-summarizer:0.1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PYTHON_PATH: /app
    env_file: .env
    ports:
      - "9999:9999"
    dns: 8.8.8.8
    network_mode: host
